admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin

store:
    resource: "@StoreBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
