<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYgbgrvo\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYgbgrvo/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerYgbgrvo.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerYgbgrvo\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerYgbgrvo\appProdProjectContainer(array(
    'container.build_hash' => 'Ygbgrvo',
    'container.build_id' => 'cc3eec43',
    'container.build_time' => 1547161835,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerYgbgrvo');
