<?php

namespace StoreBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function countPage()
    {
        $querryBuilder = $this
        ->createQueryBuilder('a')
        ->select('COUNT(a)');

        return $querryBuilder
        ->getQuery()
        ->getSingleScalarResult();
    }

    public function findByPage($indexStart, $indexEnd)
    {
        $querryBuilder = $this
        ->createQueryBuilder('a');

        return $querryBuilder
        ->setFirstResult($indexStart)
        ->setMaxResults($indexEnd)
        ->getQuery()
        ->getResult();
    }
}
