<?php

namespace StoreBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function countPage()
    {
        $queryBuilder = $this
        ->createQueryBuilder('a')
        ->select('COUNT(a)');

        return $queryBuilder
        ->getQuery()
        ->getSingleScalarResult();
    }

    public function findByPage($indexStart, $indexEnd)
    {
        $queryBuilder = $this
        ->createQueryBuilder('a');

        return $queryBuilder
        ->setFirstResult($indexStart)
        ->setMaxResults($indexEnd)
        ->getQuery()
        ->getResult();
    }

    public function getArticleAlert()
    {
        $queryBuilder = $this->createQueryBuilder('a')
                             ->where(' a.stock > 10 and a.stock < 25 ');
        return $queryBuilder
        ->getQuery()
        ->getResult();
    }
    public function getArticleDanger()
    {
        $queryBuilder = $this->createQueryBuilder('a')
                             ->where('a.stock < 10');
        return $queryBuilder
        ->getQuery()
        ->getResult();
    }
}
