StoreBundle\Entity\Category:
    type: entity
    table: null
    repositoryClass: StoreBundle\Repository\CategoryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        gender:
            type: string
            length: 255
    oneToMany:
        articles:
            targetEntity: Article
            mappedBy: category
                
    lifecycleCallbacks: {  }
