StoreBundle\Entity\Gender:
    type: entity
    table: null
    repositoryClass: StoreBundle\Repository\GenderRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        type:
            type: string
            length: 255
    oneToMany:
        category:
            targetEntity: Category
            mappedBy: gender
    lifecycleCallbacks: {  }
