<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQvvphwu\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQvvphwu/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerQvvphwu.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerQvvphwu\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerQvvphwu\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Qvvphwu',
    'container.build_id' => 'c3611585',
    'container.build_time' => 1547161793,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerQvvphwu');
